name: salat_app
description: Prayer times app for Morocco.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.1
  intl: ^0.19.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true
